apiVersion: charts.helm.k8s.io/v1alpha1
kind: SnykMonitor
metadata:
  name: snyk-monitor
  namespace: marketplace
spec:
  integrationApi: https://api.dev.snyk.io/v2/kubernetes-upstream
  temporaryStorageSize: 20Gi
  clusterName: ""
  pvc:
    enabled: true
    create: true
